---
repos:
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        stages:
          - commit
        language: system
        entry: clang-format-9 -style=file -i
        types_or:
          - c
          - c++
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint
        files: '^(\.gitlab-ci.yml|ci/)'
        args:
          - -c
          - ci/.yamllint.yml
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
        exclude: '^(\.gitlab-ci.yml|ci/)'
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
